version: '3.8'
services:
  app:
    build: .
    image: examples/test-js-app-image
    volumes:
    - ./:/app
    - /app/node_modules
    ports:
    - 8000:8000
    env_file: ./.env
    depends_on:
    - redis
    - mongo
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=123456
  redis:
    image: redis
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data
volumes:
  mongo_data: {}
  redis_data: {}
