version: '3.8'
services:
  app:
    build: .
    image: examples/test-js-app-image
    volumes:
    - ./:/app
    - /app/node_modules
    ports:
    - 8000:8000
    env_file: ./.env
    depends_on:
    - redis
    - mongo
    - postgresql
  redis:
    image: redis
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=123456
    restart: always
  postgresql:
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - postgresql_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    - POSTGRES_HOST_AUTH_METHOD=trust // do not use in production
    restart: always
volumes:
  redis_data: {}
  mongo_data: {}
  postgresql_data: {}
